In [1]:
#importing libraries
import numpy as np
import pandas as pd
import seaborn as sns
import statsmodels.api as sm
import matplotlib.pyplot as plt
from statsmodels.graphics.gofplots import ProbPlot

In [2]:
#plot settings
plt.style.use('seaborn')
plt.rc('font',size=14)
plt.rc('figure',titlesize=18)
plt.rc('axes',labelsize=15)
plt.rc('axes',titlesize=18)

In [3]:
#loding dataset
from sklearn.datasets import load_diabetes

diabetes = load_diabetes()

x=pd.DataFrame(diabetes.data,columns=diabetes.feature_names)
y=pd.DataFrame(diabetes.target)
#x = [Data]
#y = [response]

In [4]:
x.shape
y.columns = ['Glucose']
y.head()

   Glucose
0    151.0
1     75.0
2    141.0
3    206.0
4    135.0

In [5]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.25, random_state=0)

In [6]:
#create dataframe x,y for easier plot handling
dataframe = pd.concat([x,y],axis=1)
dataframe.head()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,Glucose
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019908,-0.017646,151.0
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068330,-0.092204,75.0
2,0.085299,0.050680,0.044451,-0.005671,-0.045599,-0.034194,-0.032356,-0.002592,0.002864,-0.025930,141.0
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022692,-0.009362,206.0
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031991,-0.046641,135.0

In [7]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [8]:
y_pred = regressor.predict(x_test)

In [9]:
print('intercept:\n',regressor.intercept_)
print('coefficient:\n',regressor.coef_)

intercept:
 [153.06798218]
coefficient:
 [[ -43.26774487 -208.67053951  593.39797213  302.89814903 -560.27689824
   261.47657106   -8.83343952  135.93715156  703.22658427   28.34844354]]

In [10]:
#y = 152.1335+age*(-10.0122)+sex*(-239.8191)+bmi*(519.8398)+bp*(324.3904)+s1*(-792.1842)+s2*476.7458+s3*101.0446+s4*177.0642+s5*751.27+s6*67.62

In [11]:
y_pred.shape

(111, 1)

In [12]:
from sklearn.metrics import mean_squared_error, r2_score

print('Mean Squared Error: %2f'
     % mean_squared_error(y_test,y_pred))

Mean Squared Error: 3180.198837

In [13]:
print('Variance score: %2f' %r2_score(y_test,y_pred))

Variance score: 0.359401

In [14]:
print(regressor.score(x_test,y_test))

0.35940090989715534

In [15]:
df = pd.DataFrame({'Actual':y_test['Glucose'], 'Predicted':y_pred.flatten()})
df.head()

     Actual   Predicted
362   321.0  241.847303
249   215.0  250.123039
271   127.0  164.964565
435    64.0  119.116393
400   175.0  188.231203

In [16]:
df['difference']=df['Actual']-df['Predicted']

In [17]:
df.head()

     Actual   Predicted  difference
362   321.0  241.847303   79.152697
249   215.0  250.123039  -35.123039
271   127.0  164.964565  -37.964565
435    64.0  119.116393  -55.116393
400   175.0  188.231203  -13.231203

In [18]:
df['pererror']=df['difference']/df['Actual']*100
df.head()

     Actual   Predicted  difference   pererror
362   321.0  241.847303   79.152697  24.658161
249   215.0  250.123039  -35.123039 -16.336297
271   127.0  164.964565  -37.964565 -29.893359
435    64.0  119.116393  -55.116393 -86.119365
400   175.0  188.231203  -13.231203  -7.560687

In [19]:
final = pd.concat([x_test,df],axis=1)
final.sample()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,Actual,Predicted,difference,pererror
142,0.041708,0.05068,0.012117,0.039087,0.054845,0.044406,0.00446,-0.002592,0.045601,-0.001078,235.0,172.245304,62.754696,26.704126

In [20]:
final.to_csv('Diabetes_Final.csv')

In [21]:
final[final.pererror>0]

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,Actual,Predicted,difference,pererror
362,0.019913,0.050680,0.104809,0.070073,-0.035968,-0.026679,-0.024993,-0.002592,0.003712,0.040343,321.0,241.847303,79.152697,24.658161
403,-0.020045,-0.044642,0.097264,-0.005671,-0.005697,-0.023861,-0.021311,-0.002592,0.061686,0.040343,275.0,260.560794,14.439206,5.250620
12,0.016281,-0.044642,-0.028840,-0.009113,-0.004321,-0.009769,0.044958,-0.039493,-0.030751,-0.042499,179.0,113.075838,65.924162,36.829141
399,0.059871,0.050680,0.022895,0.049415,0.016318,0.011838,-0.013948,-0.002592,0.039540,0.019633,232.0,190.541175,41.458825,17.870183
78,0.005383,-0.044642,-0.057941,-0.022885,-0.067615,-0.068328,-0.054446,-0.002592,0.042896,-0.083920,252.0,168.768441,83.231559,33.028396
298,0.023546,0.050680,-0.037463,-0.046985,-0.091006,-0.075530,-0.032356,-0.039493,-0.030751,-0.013504,129.0,109.160370,19.839630,15.379558
268,0.063504,0.050680,0.088642,0.070073,0.020446,0.037517,-0.050764,0.071210,0.029300,0.073480,264.0,244.739905,19.260095,7.295491
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068330,-0.092204,75.0,66.977350,8.022650,10.696866
10,-0.096328,-0.044642,-0.083808,0.008101,-0.103389,-0.090561,-0.013948,-0.076395,-0.062913,-0.034215,101.0,98.046734,2.953266,2.924026
37,-0.009147,-0.044642,0.011039,-0.057314,-0.024960,-0.042963,0.030232,-0.039493,0.017037,-0.005220,276.0,160.917691,115.082309,41.696489
401,0.016281,-0.044642,-0.045007,-0.057314,-0.034592,-0.053923,0.074412,-0.076395,-0.042572,0.040343,93.0,83.056692,9.943308,10.691729
319,0.019913,-0.044642,0.004572,0.045972,-0.018080,-0.054549,0.063367,-0.039493,0.028661,0.061054,191.0,189.983973,1.016027,0.531952
206,0.001751,0.050680,0.026128,-0.009113,0.024574,0.038456,-0.021311,0.034309,0.009436,0.003064,196.0,163.022796,32.977204,16.825104
375,0.045341,0.050680,-0.002973,0.107944,0.035582,0.022485,0.026550,-0.002592,0.028017,0.019633,217.0,177.078283,39.921717,18.397104
283,-0.016412,-0.044642,-0.052552,-0.033214,-0.044223,-0.036387,0.019187,-0.039493,-0.068330,-0.030072,181.0,82.670270,98.329730,54.325818
373,-0.074533,-0.044642,-0.010517,-0.005671,-0.066239,-0.057054,-0.002903,-0.039493,-0.042572,-0.001078,168.0,144.532050,23.467950,13.969018
344,-0.107226,-0.044642,-0.011595,-0.040099,0.049341,0.064447,-0.013948,0.034309,0.007027,-0.030072,200.0,146.079016,53.920984,26.960492
287,0.045341,-0.044642,-0.006206,-0.015999,0.125019,0.125198,0.019187,0.034309,0.032433,-0.005220,219.0,141.738413,77.261587,35.279264
360,0.016281,-0.044642,0.020739,0.021872,-0.013953,-0.013214,-0.006584,-0.002592,0.013316,0.040343,281.0,195.186582,85.813418,30.538583
238,0.034443,0.050680,-0.009439,0.059744,-0.035968,-0.007577,-0.076536,0.071210,0.011008,-0.021788,257.0,189.147689,67.852311,26.401677
158,-0.012780,-0.044642,-0.065486,-0.069938,0.001183,0.016849,-0.002903,-0.007020,-0.030751,-0.050783,96.0,82.642735,13.357265,13.913817
118,-0.056370,0.050680,-0.010517,0.025315,0.023198,0.040022,-0.039719,0.034309,0.020612,0.056912,179.0,164.949126,14.050874,7.849650
397,0.052606,-0.044642,-0.004050,-0.030918,-0.046975,-0.058307,-0.013948,-0.025840,0.036056,0.023775,198.0,182.051982,15.948018,8.054554
330,0.009016,0.050680,0.030440,0.042530,-0.002945,0.036890,-0.065491,0.071210,-0.023645,0.015491,244.0,178.413556,65.586444,26.879690
296,0.067136,-0.044642,-0.061174,-0.040099,-0.026336,-0.024487,0.033914,-0.039493,-0.056158,-0.059067,89.0,72.550409,16.449591,18.482687
164,0.045341,-0.044642,-0.019140,0.021872,0.027326,-0.013527,0.100183,-0.039493,0.017763,-0.013504,214.0,142.697504,71.302496,33.318923
54,-0.049105,-0.044642,0.025051,0.008101,0.020446,0.017788,0.052322,-0.039493,-0.041180,0.007207,182.0,140.436715,41.563285,22.836970
71,-0.001882,-0.044642,0.033673,0.125158,0.024574,0.026243,-0.010266,-0.002592,0.026714,0.061054,270.0,233.705536,36.294464,13.442394
6,-0.045472,0.050680,-0.047163,-0.015999,-0.040096,-0.024800,0.000779,-0.039493,-0.062913,-0.038357,138.0,76.902704,61.097296,44.273403
282,0.070769,-0.044642,-0.005128,-0.005671,0.087868,0.102965,0.011824,0.034309,-0.008944,0.027917,230.0,131.314286,98.685714,42.906832
142,0.041708,0.050680,0.012117,0.039087,0.054845,0.044406,0.004460,-0.002592,0.045601,-0.001078,235.0,172.245304,62.754696,26.704126
102,-0.092695,-0.044642,0.028284,-0.015999,0.036958,0.024991,0.056003,-0.039493,-0.005145,-0.001078,302.0,154.647362,147.352638,48.792264
141,-0.027310,-0.044642,0.047685,-0.046985,0.034206,0.057245,-0.080217,0.130252,0.045066,0.131470,317.0,227.266104,89.733896,28.307223
441,-0.045472,-0.044642,-0.073030,-0.081414,0.083740,0.027809,0.173816,-0.039493,-0.004220,0.003064,57.0,46.923830,10.076170,17.677490
90,0.012648,-0.044642,-0.025607,-0.040099,-0.030464,-0.045155,0.078093,-0.076395,-0.072128,0.011349,98.0,78.280982,19.719018,20.121447
59,0.063504,0.050680,-0.025607,0.011544,0.064477,0.048477,0.030232,-0.002592,0.038393,0.019633,170.0,131.533521,38.466479,22.627341
438,-0.005515,0.050680,-0.015906,-0.067642,0.049341,0.079165,-0.028674,0.034309,-0.018118,0.044485,104.0,99.295735,4.704265,4.523331
276,0.012648,-0.044642,0.026128,0.063187,0.125019,0.091691,0.063367,-0.002592,0.057573,-0.021788,283.0,189.366814,93.633186,33.085931
113,0.019913,0.050680,0.014272,0.063187,0.014942,0.020293,-0.047082,0.034309,0.046661,0.090049,297.0,206.619258,90.380742,30.431226
381,-0.070900,0.050680,-0.089197,-0.074528,-0.042848,-0.025739,-0.032356,-0.002592,-0.012908,-0.054925,104.0,76.631627,27.368373,26.315743
26,-0.107226,-0.044642,-0.077342,-0.026328,-0.089630,-0.096198,0.026550,-0.076395,-0.042572,-0.005220,137.0,97.512725,39.487275,28.822829
154,0.067136,0.050680,0.020739,-0.005671,0.020446,0.026243,-0.002903,-0.002592,0.008640,0.003064,197.0,151.419373,45.580627,23.137374
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031991,-0.046641,135.0,124.814638,10.185362,7.544713
327,0.074401,-0.044642,0.114509,0.028758,0.024574,0.024991,0.019187,-0.002592,-0.000609,-0.005220,237.0,227.492222,9.507778,4.011721
264,0.034443,0.050680,0.028284,-0.033214,-0.045599,-0.009769,-0.050764,-0.002592,-0.059473,-0.021788,145.0,128.375181,16.624819,11.465392
190,0.009016,-0.044642,-0.012673,0.028758,-0.018080,-0.005072,-0.047082,0.034309,0.023375,-0.005220,292.0,193.357529,98.642471,33.781668
200,0.056239,-0.044642,-0.057941,-0.007966,0.052093,0.049103,0.056003,-0.021412,-0.028320,0.044485,158.0,84.748037,73.251963,46.362002
68,0.038076,0.050680,-0.029918,-0.040099,-0.033216,-0.024174,-0.010266,-0.002592,-0.012908,0.003064,160.0,113.983084,46.016916,28.760572